
export const getWhatsAppStyles = () => {
    return {
        container: {
            minHeight: "100vh",
            backgroundColor: "#f8f9fa",
            padding: "20px",
            overflowY: "auto",
            maxHeight: "100vh",
        },
        header: {
            backgroundColor: "#fff",
            borderRadius: "12px",
            padding: "30px",
            marginBottom: "30px",
            boxShadow: "0 2px 10px rgba(0,0,0,0.1)",
            textAlign: "center",
            border: "1px solid #e9ecef",
        },
        title: {
            color: "#343a40",
            fontSize: "2.5rem",
            fontWeight: "600",
            marginBottom: "10px",
            fontFamily: "Segoe UI, Tahoma, Geneva, Verdana, sans-serif",
        },
        subtitle: {
            color: "#6c757d",
            fontSize: "1.1rem",
            marginBottom: "0",
        },
        navTabs: {
            backgroundColor: "#fff",
            borderRadius: "12px",
            padding: "8px",
            marginBottom: "30px",
            boxShadow: "0 2px 10px rgba(0,0,0,0.1)",
            display: "flex",
            gap: "8px",
            border: "1px solid #e9ecef",
        },
        tab: {
            flex: 1,
            padding: "15px 20px",
            backgroundColor: "transparent",
            border: "none",
            borderRadius: "8px",
            cursor: "pointer",
            fontSize: "16px",
            fontWeight: "500",
            transition: "all 0.3s ease",
            color: "#6c757d",
        },
        activeTab: {
            backgroundColor: "#007bff",
            color: "#fff",
            transform: "translateY(-2px)",
            boxShadow: "0 4px 12px rgba(0,123,255,0.3)",
        },
        content: {
            backgroundColor: "#fff",
            borderRadius: "12px",
            padding: "30px",
            boxShadow: "0 2px 10px rgba(0,0,0,0.1)",
            border: "1px solid #e9ecef",
            marginBottom: "20px",
        },
        statusCard: {
            padding: "25px",
            borderRadius: "12px",
            marginBottom: "30px",
            textAlign: "center",
        },
        statusIcon: {
            fontSize: "3rem",
            marginBottom: "15px",
            display: "block",
        },
        statusText: {
            fontSize: "1.5rem",
            fontWeight: "600",
            marginBottom: "10px",
        },
        statusSubtext: {
            color: "#6c757d",
            fontSize: "1rem",
        },
        grid: {
            display: "grid",
            gridTemplateColumns: "repeat(auto-fit, minmax(400px, 1fr))",
            gap: "30px",
            marginBottom: "30px",
        },
        card: {
            backgroundColor: "#fff",
            borderRadius: "12px",
            padding: "25px",
            boxShadow: "0 2px 10px rgba(0,0,0,0.1)",
            border: "1px solid #e9ecef",
        },
        cardTitle: {
            fontSize: "1.4rem",
            fontWeight: "600",
            color: "#343a40",
            marginBottom: "20px",
            display: "flex",
            alignItems: "center",
            gap: "10px",
        },
        formGroup: {
            marginBottom: "20px",
        },
        label: {
            display: "block",
            marginBottom: "8px",
            fontWeight: "500",
            color: "#495057",
            fontSize: "0.95rem",
        },
        input: {
            width: "100%",
            padding: "12px 16px",
            border: "2px solid #e9ecef",
            borderRadius: "8px",
            fontSize: "16px",
            transition: "border-color 0.3s ease",
            fontFamily: "inherit",
        },
        inputFocus: {
            borderColor: "#007bff",
            boxShadow: "0 0 0 3px rgba(0,123,255,0.1)",
        },
        textarea: {
            width: "100%",
            padding: "12px 16px",
            border: "2px solid #e9ecef",
            borderRadius: "8px",
            fontSize: "16px",
            minHeight: "120px",
            resize: "vertical",
            transition: "border-color 0.3s ease",
            fontFamily: "inherit",
        },
        select: {
            width: "100%",
            padding: "12px 16px",
            border: "2px solid #e9ecef",
            borderRadius: "8px",
            fontSize: "16px",
            backgroundColor: "#fff",
            transition: "border-color 0.3s ease",
        },
        button: {
            backgroundColor: "#007bff",
            color: "#fff",
            padding: "12px 24px",
            border: "none",
            borderRadius: "8px",
            fontSize: "16px",
            fontWeight: "500",
            cursor: "pointer",
            transition: "all 0.3s ease",
            display: "inline-flex",
            alignItems: "center",
            gap: "8px",
        },
        buttonHover: {
            backgroundColor: "#0056b3",
            transform: "translateY(-2px)",
            boxShadow: "0 4px 12px rgba(0,123,255,0.3)",
        },
        buttonSuccess: {
            backgroundColor: "#28a745",
        },
        buttonDanger: {
            backgroundColor: "#dc3545",
        },
        buttonWarning: {
            backgroundColor: "#ffc107",
            color: "#212529",
        },
        buttonSecondary: {
            backgroundColor: "#6c757d",
        },
        buttonDisabled: {
            backgroundColor: "#e9ecef",
            color: "#6c757d",
            cursor: "not-allowed",
        },
        buttonGroup: {
            display: "flex",
            gap: "12px",
            flexWrap: "wrap",
        },
        qrContainer: {
            backgroundColor: "#fff",
            padding: "30px",
            borderRadius: "12px",
            marginBottom: "30px",
            textAlign: "center",
            border: "2px solid #ffc107",
            boxShadow: "0 4px 20px rgba(255,193,7,0.2)",
        },
        qrCode: {
            maxWidth: "280px",
            margin: "20px auto",
            display: "block",
            borderRadius: "12px",
            boxShadow: "0 4px 20px rgba(0,0,0,0.1)",
        },
        listItem: {
            backgroundColor: "#f8f9fa",
            padding: "20px",
            marginBottom: "15px",
            borderRadius: "12px",
            border: "1px solid #e9ecef",
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            transition: "all 0.3s ease",
        },
        listItemHover: {
            boxShadow: "0 4px 12px rgba(0,0,0,0.1)",
            transform: "translateY(-2px)",
        },
        listContent: {
            flex: 1,
        },
        listTitle: {
            fontWeight: "600",
            color: "#343a40",
            fontSize: "1.1rem",
            marginBottom: "8px",
        },
        listMeta: {
            color: "#6c757d",
            fontSize: "0.9rem",
            marginBottom: "4px",
        },
        statsGrid: {
            display: "grid",
            gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
            gap: "20px",
            marginBottom: "30px",
        },
        statCard: {
            padding: "20px",
            backgroundColor: "#f8f9fa",
            borderRadius: "12px",
            textAlign: "center",
            border: "1px solid #e9ecef",
            transition: "all 0.3s ease",
        },
        statNumber: {
            fontSize: "2rem",
            fontWeight: "700",
            color: "#343a40",
            marginBottom: "8px",
        },
        statLabel: {
            color: "#6c757d",
            fontSize: "0.9rem",
            fontWeight: "500",
        },
        logsContainer: {
            maxHeight: "500px",
            overflowY: "auto",
            border: "1px solid #e9ecef",
            borderRadius: "12px",
            padding: "15px",
            backgroundColor: "#f8f9fa",
        },
        logItem: {
            padding: "15px",
            marginBottom: "12px",
            backgroundColor: "#fff",
            borderRadius: "8px",
            borderLeft: "4px solid #007bff",
            boxShadow: "0 2px 4px rgba(0,0,0,0.05)",
        },
        logHeader: {
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            marginBottom: "8px",
        },
        logType: {
            fontWeight: "600",
            fontSize: "0.85rem",
            padding: "4px 8px",
            borderRadius: "4px",
            backgroundColor: "#e9ecef",
        },
        logTime: {
            fontSize: "0.8rem",
            color: "#6c757d",
        },
        logMessage: {
            fontSize: "0.9rem",
            lineHeight: "1.4",
            color: "#495057",
        },
        userInfoCard: {
            background: "linear-gradient(135deg, #28a74515, #28a74505)",
            padding: "25px",
            borderRadius: "12px",
            marginBottom: "30px",
            border: "2px solid #28a745",
        },
        userAvatar: {
            width: "60px",
            height: "60px",
            borderRadius: "50%",
            margin: "0 auto 15px",
            display: "block",
        },
        helpBox: {
            backgroundColor: "#e3f2fd",
            padding: "20px",
            borderRadius: "12px",
            marginBottom: "30px",
            border: "1px solid #bbdefb",
        },
        helpTitle: {
            color: "#1976d2",
            fontWeight: "600",
            marginBottom: "15px",
            fontSize: "1.2rem",
        },
        helpList: {
            color: "#424242",
            lineHeight: "1.6",
        },
        contactItem: {
            backgroundColor: "#f8f9fa",
            padding: "15px",
            marginBottom: "15px",
            borderRadius: "8px",
            border: "1px solid #e9ecef",
        },
        contactItemHeader: {
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            marginBottom: "10px",
        },
        contactPhone: {
            fontWeight: "600",
            color: "#343a40",
        },
        contactDetails: {
            fontSize: "0.85rem",
            color: "#6c757d",
            marginBottom: "5px",
        },
        smallButton: {
            padding: "4px 8px",
            fontSize: "0.8rem",
            minWidth: "auto",
        },
    };
};

export default getWhatsAppStyles;
