const styles = {
    pageContainer: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      width: "100%",
      height: "100%",
      backgroundColor: "#d4e4ff",
      overflowY: "auto",
      padding: "20px",
    },
    editorToolbar: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: "10px",
      padding: "10px",
      backgroundColor: "#f0f0f0",
      borderRadius: "8px",
      marginBottom: "10px",
      boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
      width: "793.7px",
      flexWrap: "wrap",
      position: "sticky",
      top: 0,
      zIndex: 100,
    },
    toolbarGroup: {
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      gap: "5px",
      borderRight: "1px solid #ddd",
      paddingRight: "10px",
      marginRight: "10px",
    },
    toolbarButton: {
      padding: "6px 10px",
      backgroundColor: "#fff",
      border: "1px solid #ccc",
      borderRadius: "4px",
      cursor: "pointer",
      fontSize: "14px",
      color: "#333",
      transition: "all 0.2s ease",
      minWidth: "32px",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
    },
    toolbarSelect: {
      padding: "6px 10px",
      backgroundColor: "#fff",
      border: "1px solid #ccc",
      borderRadius: "4px",
      cursor: "pointer",
      fontSize: "14px",
      color: "#333",
      minWidth: "120px",
    },
    colorPicker: {
      width: "30px",
      height: "30px",
      padding: "0",
      border: "1px solid #ccc",
      borderRadius: "4px",
      cursor: "pointer",
      backgroundColor: "transparent",
    },
    toolbarLabel: {
      display: "flex",
      alignItems: "center",
      cursor: "pointer",
      padding: "4px 8px",
      borderRadius: "4px",
      backgroundColor: "#fff",
      border: "1px solid #ccc",
    },
    body: {
      margin: 0,
      padding: 0,
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      minHeight: "100vh",
      backgroundColor: "#d4e4ff",
    },
    header: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      width: "100%",
      padding: "15px 20px",
      backgroundColor: "#d4e4ff",
      color: "#fff",
      marginBottom: "20px",
    },
    controlsAlignedLeft: {
      display: "flex",
      flexWrap: "wrap",
      gap: "10px",
      justifyContent: "center",
      alignItems: "center",
    },
    input: {
      width: "100%",
      padding: "10px",
      fontSize: "16px",
      border: "1px solid #ccc",
      borderRadius: "5px",
      marginBottom: "10px",
      boxSizing: "border-box",
    },
    textarea: {
      width: "100%",
      padding: "10px",
      fontSize: "16px",
      border: "1px solid #ccc",
      borderRadius: "5px",
      height: "300px",
      resize: "none",
      whiteSpace: "pre-wrap",
      boxSizing: "border-box",
    },
    fileInputLabel: {
      display: "flex",
      alignItems: "center",
      gap: "10px",
      padding: "10px 20px",
      fontSize: "16px",
      color: "#fff",
      backgroundColor: "#1792FE",
      border: "none",
      borderRadius: "6px",
      cursor: "pointer",
      transition: "background-color 0.3s ease",
      marginTop: "10px",
    },
    fileInput: {
      display: "none",
    },
    button: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      padding: "10px 20px",
      fontSize: "16px",
      color: "#fff",
      backgroundColor: "#1792fe",
      border: "none",
      borderRadius: "8px",
      cursor: "pointer",
      transition: "background-color 0.3s ease",
      boxShadow: "0 2px 5px rgba(0, 0, 0, 0.1)",
      margin: "0 !important",
    },
    docxContainer: {
      marginTop: "20px",
      width: "793.7px",
      height: "1122.5px",
      border: "0px solid #ccc",
      backgroundColor: "#fff",
      padding: "20px",
      borderRadius: "8px",
      boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
    },
    removeButton: {
      backgroundColor: "#1792FE",
      color: "#fff",
      border: "none",
      padding: "5px 10px",
      marginLeft: "10px",
      cursor: "pointer",
      borderRadius: "5px",
      fontSize: "14px",
      transition: "background-color 0.3s ease",
    },
    anexosList: {
      marginTop: "15px",
      padding: "15px",
      backgroundColor: "#eef",
      border: "1px solid #ccc",
      borderRadius: "8px",
      width: "100%",
      maxWidth: "600px",
    },
    h4: {
      color: "#333",
      fontSize: "18px",
      marginBottom: "10px",
    },
    ul: {
      listStyleType: "none",
      paddingLeft: "0",
      margin: "0",
      color: "#333",
    },
    li: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      padding: "8px 10px",
      marginBottom: "5px",
      border: "1px solid #ddd",
      borderRadius: "6px",
      backgroundColor: "#fff",
      fontSize: "14px",
      transition: "box-shadow 0.3s ease",
    },
    cancelButton: {
      display: "flex",
      alignItems: "center",
      gap: "8px",
      padding: "10px 20px",
      fontSize: "16px",
      color: "#fff",
      backgroundColor: "#999",
      border: "none",
      borderRadius: "6px",
      cursor: "pointer",
      transition: "background-color 0.3s ease",
    },
    modalOverlay: {
      position: "fixed",
      top: 0,
      left: 0,
      width: "100%",
      height: "100%",
      backgroundColor: "rgba(0, 0, 0, 0.5)",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      zIndex: 1000,
    },
    modalContent: {
      backgroundColor: "#fff",
      padding: "30px",
      borderRadius: "10px",
      width: "700px",
      maxWidth: "90%",
      maxHeight: "90vh",
      overflowY: "auto",
      boxShadow: "0 4px 8px rgba(0, 0, 0, 0.2)",
      textAlign: "center",
    },
    signatureSection: {
      marginTop: "15px",
      marginBottom: "15px",
      border: "1px solid #eee",
      borderRadius: "8px",
      padding: "10px",
      backgroundColor: "#f9f9f9",
    },
    signatureHeader: {
      display: "flex",
      alignItems: "center",
      gap: "10px",
      marginBottom: "10px",
      padding: "5px 0",
      borderBottom: "1px solid #eee",
    },
    signaturePreview: {
      backgroundColor: "#fff",
      border: "1px solid #eee",
      borderRadius: "5px",
      padding: "15px",
      maxHeight: "250px",
      overflowY: "auto",
    },
    signatureTable: {
      width: "100%",
      borderCollapse: "collapse",
    },
    signatureMainContent: {
      width: "70%",
      padding: "10px",
      verticalAlign: "top",
      textAlign: "left",
    },
    signatureLogoContainer: {
      width: "30%",
      padding: "10px",
      verticalAlign: "top",
      textAlign: "center",
    },
    modalTitle: {
      fontSize: "20px",
      fontWeight: "600",
      color: "#333",
      marginBottom: "15px",
    },
    modalMessage: {
      fontSize: "16px",
      color: "#555",
      marginBottom: "20px",
      lineHeight: "1.5",
    },
    modalActions: {
      marginTop: "20px",
      marginBottom: "50px",
      display: "flex",
      justifyContent: "center",
      gap: "5px",
    },
    formContainer: {
      maxWidth: "600px",
      margin: "0 auto",
      padding: "20px",
      backgroundColor: "#ffffff",
      borderRadius: "12px",
      boxShadow: "0 4px 10px rgba(0, 0, 0, 0.1)",
      textAlign: "center",
      width: "100%",
    },
  };
  
  export default styles;
  