const styles = {
    
    container: {
        flex: 1,
        backgroundColor: '#d4e4ff',
    },
    header: {
        width: '100%',
    },
    headerGradient: {
        borderBottomLeftRadius: 25,
        borderBottomRightRadius: 25,
        paddingTop: 40,
        paddingBottom: 30,
        paddingHorizontal: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 5,
    },
    headerContent: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    headerTitle: {
        fontSize: 26,
        fontWeight: '700',
        color: '#ffffff',
        marginTop: 4,
    },
    dateText: {
        fontSize: 14,
        color: 'rgba(255, 255, 255, 0.9)',
        fontWeight: '500',
    },
    historyButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    content: {
        flex: 1,
        padding: 16,
    },
    timerCard: {
        backgroundColor: '#ffffff',
        borderRadius: 20,
        marginTop: -20,
        padding: 20,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 6,
        elevation: 3,
    },
    statusBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 6,
        paddingHorizontal: 14,
        borderRadius: 20,
        marginBottom: 20,
    },
    statusText: {
        color: '#ffffff',
        fontWeight: '600',
        marginLeft: 6,
        fontSize: 15,
    },
    timerDisplay: {
        backgroundColor: '#f6f8fa',
        width: '100%',
        paddingVertical: 30,
        borderRadius: 14,
        marginBottom: 25,
        alignItems: 'center',
    },
    timerText: {
        fontSize: 40,
        fontWeight: '700',
        color: '#333',
        fontFamily: 'monospace',
        letterSpacing: 2,
    },
    actionButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
    },
    actionButton: {
        flex: 1,
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
        borderRadius: 12,
        marginHorizontal: 6,
    },
    startButton: {
        backgroundColor: '#4CAF50',
    },
    pauseButton: {
        backgroundColor: '#FF9800',
    },
    resumeButton: {
        backgroundColor: '#2196F3',
    },
    disabledButton: {
        backgroundColor: '#E0E0E0',
        opacity: 0.7,
    },
    actionButtonText: {
        color: '#ffffff',
        fontWeight: '600',
        marginTop: 6,
        fontSize: 14,
    },
    todaySummary: {
        backgroundColor: '#ffffff',
        borderRadius: 20,
        marginTop: 20,
        padding: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 6,
        elevation: 2,
    },
    todayHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 15,
    },
    todayTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#333',
    },
    timeRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    timeItem: {
        flex: 1,
        backgroundColor: '#f5f7fa',
        padding: 14,
        borderRadius: 12,
        alignItems: 'center',
    },
    timeArrow: {
        paddingHorizontal: 10,
    },
    timeLabel: {
        fontSize: 13,
        color: '#777',
        marginBottom: 5,
    },
    timeValue: {
        fontSize: 18,
        fontWeight: '600',
        color: '#333',
    },
    statsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 20,
    },
    statBox: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f5f7fa',
        padding: 16,
        borderRadius: 12,
        marginHorizontal: 5,
    },
    statLabel: {
        fontSize: 12,
        color: '#777',
        marginLeft: 10,
    },
    statValue: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
        marginLeft: 10,
    },
    locationButton: {
        backgroundColor: '#4481EB',
        borderRadius: 12,
        paddingVertical: 14,
        paddingHorizontal: 20,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
    },
    locationButtonText: {
        color: '#ffffff',
        fontWeight: '600',
        marginLeft: 8,
        fontSize: 15,
    },
    emptyState: {
        alignItems: 'center',
        justifyContent: 'center',
        padding: 40,
        marginTop: 20,
    },
    emptyStateTitle: {
        fontSize: 20,
        fontWeight: '600',
        color: '#333',
        marginTop: 20,
        marginBottom: 8,
    },
    emptyStateText: {
        fontSize: 15,
        color: '#777',
        textAlign: 'center',
        maxWidth: '80%',
    },

}

export default styles;
  