import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f5f7fa',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#f5f7fa',
    },
    loadingText: {
        marginTop: 16,
        fontSize: 16,
        color: '#666',
    },
    header: {
        backgroundColor: '#1792FE',
        paddingVertical: 20,
        paddingHorizontal: 20,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    headerContent: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    headerTitle: {
        fontSize: 24,
        fontWeight: '700',
        color: '#fff',
    },
    headerActions: {
        flexDirection: 'row',
        gap: 12,
    },
    filterButton: {
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        padding: 10,
        borderRadius: 8,
    },
    exportButton: {
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        padding: 10,
        borderRadius: 8,
    },
    filtersContainer: {
        backgroundColor: '#fff',
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#e0e0e0',
    },
    filterLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#333',
        marginBottom: 8,
    },
    filterButtons: {
        flexDirection: 'row',
        gap: 8,
    },
    filterOption: {
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 20,
        backgroundColor: '#f0f0f0',
        borderWidth: 1,
        borderColor: '#ddd',
    },
    filterOptionActive: {
        backgroundColor: '#1792FE',
        borderColor: '#1792FE',
    },
    filterOptionText: {
        fontSize: 12,
        color: '#666',
        fontWeight: '500',
    },
    filterOptionTextActive: {
        color: '#fff',
    },
    content: {
        flex: 1,
        padding: 16,
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#333',
        marginBottom: 16,
    },
    kpisContainer: {
        marginBottom: 24,
    },
    kpisGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
    },
    kpiCard: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 16,
        flex: 1,
        minWidth: 150,
        borderLeftWidth: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    kpiHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    kpiValue: {
        fontSize: 24,
        fontWeight: '700',
        color: '#333',
        marginBottom: 4,
    },
    kpiTitle: {
        fontSize: 12,
        color: '#666',
        fontWeight: '500',
    },
    chartContainer: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 16,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    chartTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#333',
        marginBottom: 16,
        textAlign: 'center',
    },
    simplePieContainer: {
        alignItems: 'center',
    },
    pieItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginVertical: 4,
        width: '100%',
    },
    pieColor: {
        width: 16,
        height: 16,
        borderRadius: 8,
        marginRight: 8,
    },
    pieLabel: {
        fontSize: 14,
        color: '#333',
    },
    simpleBarContainer: {
        gap: 12,
    },
    barItem: {
        marginBottom: 8,
    },
    barLabel: {
        fontSize: 14,
        fontWeight: '500',
        color: '#333',
        marginBottom: 4,
    },
    barBackground: {
        height: 20,
        backgroundColor: '#f0f0f0',
        borderRadius: 10,
        overflow: 'hidden',
    },
    barFill: {
        height: '100%',
        borderRadius: 10,
    },
    barValue: {
        fontSize: 12,
        color: '#666',
        textAlign: 'center',
        marginTop: 2,
    },
    tecnicoCard: {
        backgroundColor: '#f8f9fa',
        borderRadius: 8,
        padding: 12,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#e9ecef',
    },
    tecnicoHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    tecnicoRank: {
        flexDirection: 'row',
        alignItems: 'center',
        marginRight: 12,
        minWidth: 40,
    },
    rankNumber: {
        fontSize: 16,
        fontWeight: '700',
        color: '#1792FE',
        marginRight: 4,
    },
    tecnicoNome: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
        flex: 1,
    },
    tecnicoStats: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    stat: {
        alignItems: 'center',
        flex: 1,
    },
    statValue: {
        fontSize: 16,
        fontWeight: '700',
        color: '#1792FE',
    },
    statLabel: {
        fontSize: 12,
        color: '#666',
        marginTop: 2,
    },
    progressBar: {
        height: 4,
        backgroundColor: '#e9ecef',
        borderRadius: 2,
        overflow: 'hidden',
    },
    progressFill: {
        height: '100%',
        backgroundColor: '#1792FE',
    },
    pedidoCard: {
        backgroundColor: '#f8f9fa',
        borderRadius: 8,
        padding: 12,
        marginBottom: 8,
        borderWidth: 1,
        borderColor: '#e9ecef',
        borderLeftWidth: 4,
        borderLeftColor: '#ffc107',
    },
    pedidoHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    pedidoNumero: {
        fontSize: 16,
        fontWeight: '700',
        color: '#333',
    },
    statusBadge: {
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
    },
    statusText: {
        fontSize: 10,
        fontWeight: '600',
        color: '#fff',
    },
    pedidoCliente: {
        fontSize: 14,
        color: '#333',
        marginBottom: 4,
        fontWeight: '600',
    },
    pedidoTecnico: {
        fontSize: 13,
        color: '#666',
        marginBottom: 4,
    },
    pedidoTipo: {
        fontSize: 13,
        color: '#666',
        marginBottom: 4,
    },
    pedidoData: {
        fontSize: 12,
        color: '#888',
        marginBottom: 4,
    },
    pedidoDescricao: {
        fontSize: 12,
        color: '#555',
        fontStyle: 'italic',
        marginTop: 4,
    },
});

export default styles;
