
export const styles = {
    container: {
        flex: 1,
    },
    headerContainer: {
        marginBottom: 20,
    },
    headerGradient: {
        paddingTop: 50,
        paddingBottom: 30,
        paddingHorizontal: 20,
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
    },
    headerContent: {
        alignItems: "center",
    },
    headerIcon: {
        marginBottom: 10,
    },
    headerTitle: {
        fontSize: 28,
        fontWeight: "bold",
        color: "#FFFFFF",
        textAlign: "center",
        marginBottom: 5,
    },
    headerSubtitle: {
        fontSize: 16,
        color: "rgba(255,255,255,0.9)",
        textAlign: "center",
    },
    searchContainer: {
        marginHorizontal: 20,
        marginBottom: 20,
        borderRadius: 25,
        padding: 5,
    },
    searchInputContainer: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#FFFFFF",
        borderRadius: 20,
        paddingHorizontal: 15,
        elevation: 3,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    searchIcon: {
        marginRight: 10,
    },
    searchInput: {
        flex: 1,
        height: 45,
        fontSize: 16,
        color: "#333",
    },
    clearButton: {
        padding: 5,
    },
    filtersContainer: {
        marginHorizontal: 20,
        marginBottom: 20,
        backgroundColor: "rgba(255,255,255,0.9)",
        borderRadius: 15,
        padding: 15,
    },
    filtersTitle: {
        fontSize: 16,
        fontWeight: "600",
        color: "#333",
        marginBottom: 12,
    },
    filterButtons: {
        flexDirection: "row",
        gap: 8,
    },
    filterButton: {
        flex: 1,
        borderRadius: 10,
        overflow: "hidden",
    },
    filterButtonGradient: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 10,
        paddingHorizontal: 12,
    },
    filterButtonText: {
        fontSize: 12,
        fontWeight: "600",
        color: "#666",
        marginLeft: 6,
        textAlign: "center",
    },
    filterButtonTextActive: {
        color: "#FFFFFF",
    },
    filterButtonActive: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
    },
    listContainer: {
        paddingHorizontal: 20,
        paddingBottom: 20,
    },
    obraCard: {
        marginBottom: 15,
        borderRadius: 15,
        elevation: 5,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.15,
        shadowRadius: 6,
    },
    cardGradient: {
        borderRadius: 15,
        overflow: "hidden",
    },
    cardHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        padding: 20,
    },
    cardHeaderLeft: {
        flexDirection: "row",
        alignItems: "center",
        flex: 1,
    },
    iconContainer: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: "rgba(23,146,254,0.1)",
        alignItems: "center",
        justifyContent: "center",
        marginRight: 15,
    },
    cardHeaderText: {
        flex: 1,
    },
    obraTitle: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#333",
        marginBottom: 3,
    },
    obraCodigo: {
        fontSize: 14,
        color: "#666",
    },
    cardContent: {
        paddingHorizontal: 20,
        paddingBottom: 20,
    },
    detailRow: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 12,
        paddingVertical: 5,
    },
    detailLabel: {
        fontSize: 14,
        fontWeight: "600",
        color: "#555",
        marginLeft: 10,
        marginRight: 10,
        minWidth: 70,
    },
    detailValue: {
        fontSize: 14,
        color: "#333",
        flex: 1,
    },
    qrContainer: {
        alignItems: "center",
        marginTop: 15,
        padding: 15,
        backgroundColor: "rgba(23,146,254,0.05)",
        borderRadius: 10,
    },
    qrTitle: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#1792FE",
        marginBottom: 10,
    },
    qrCodeWrapper: {
        backgroundColor: "#FFFFFF",
        padding: 10,
        borderRadius: 10,
        elevation: 2,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    qrCodeImage: {
        width: 120,
        height: 120,
    },
    importButton: {
        marginTop: 15,
        borderRadius: 10,
        overflow: "hidden",
    },
    detailsButton: {
        marginTop: 15,
        borderRadius: 10,
        overflow: "hidden",
    },
    mapaButton: {
        marginTop: 15,
        borderRadius: 10,
        overflow: "hidden",
    },
    buttonGradient: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 12,
        paddingHorizontal: 20,
    },
    buttonText: {
        color: "#FFFFFF",
        fontSize: 16,
        fontWeight: "bold",
        marginLeft: 8,
    },
    emptyContainer: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 40,
        marginTop: 50,
    },
    emptyTitle: {
        fontSize: 24,
        fontWeight: "bold",
        color: "#666",
        marginTop: 20,
        marginBottom: 10,
        textAlign: "center",
    },
    emptySubtitle: {
        fontSize: 16,
        color: "#999",
        textAlign: "center",
        lineHeight: 24,
    },
    loadingContainer: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
    },
    loadingContent: {
        alignItems: "center",
    },
    loadingText: {
        fontSize: 18,
        color: "#1792FE",
        marginTop: 15,
        fontWeight: "600",
        marginBottom: 20,
    },
    progressContainer: {
        width: "80%",
        alignItems: "center",
    },
    progressBar: {
        width: "100%",
        height: 8,
        backgroundColor: "#e0e0e0",
        borderRadius: 4,
        overflow: "hidden",
    },
    progressFill: {
        height: "100%",
        backgroundColor: "#1792FE",
        borderRadius: 4,
    },
    progressText: {
        fontSize: 14,
        color: "#666",
        marginTop: 8,
        fontWeight: "500",
    },
    errorContainer: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 40,
    },
    errorTitle: {
        fontSize: 24,
        fontWeight: "bold",
        color: "#dc3545",
        marginTop: 20,
        marginBottom: 10,
        textAlign: "center",
    },
    errorMessage: {
        fontSize: 16,
        color: "#666",
        textAlign: "center",
        marginBottom: 30,
        lineHeight: 24,
    },
    retryButton: {
        borderRadius: 10,
        overflow: "hidden",
    },
    headerMapaButton: {
        marginTop: 15,
        borderRadius: 25,
        overflow: "hidden",
        elevation: 3,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
    },
    headerMapaButtonGradient: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 12,
        paddingHorizontal: 20,
    },
    headerMapaButtonText: {
        color: "#FFFFFF",
        fontSize: 16,
        fontWeight: "600",
        marginLeft: 8,
    },
};
