import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    cellEditado: {
        backgroundColor: '#fff3cd',
    },
    externoSubmetidoRow: {
        backgroundColor: '#eefaf0',
    },
    externoLinha: {
        backgroundColor: '#f8f9fa',
        borderWidth: 1,
        borderColor: '#e0e0e0',
        paddingVertical: 10,
        paddingHorizontal: 12,
        borderRadius: 10,
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },

    // Modal de externos
    externosModalContainer: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 10,
    },
    externosModalContent: {
        backgroundColor: '#FFFFFF',
        width: '100%',
        maxWidth: 800,
        maxHeight: '90%',
        borderRadius: 20,
        elevation: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 5 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
        overflow: 'hidden',
    },
    externosModalHeader: {
        paddingHorizontal: 20,
        paddingTop: 20,
        paddingBottom: 15,
    },
    externosModalHeaderContent: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    externosModalTitleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    externosModalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#fff',
    },
    externosModalSubtitle: {
        fontSize: 14,
        color: 'rgba(255,255,255,0.9)',
        marginTop: 5,
    },
    externosCloseButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: 'rgba(255,255,255,0.2)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    externosModalBody: {
        flex: 1,
        paddingHorizontal: 20,
        paddingTop: 15,
    },
    externosFormCard: {
        backgroundColor: '#f8f9fa',
        borderRadius: 16,
        padding: 20,
        marginBottom: 15,
        borderWidth: 1,
        borderColor: '#e9ecef',
    },
    externosFormTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#333',
        marginBottom: 20,
        textAlign: 'center',
    },
    externosFormGrid: {
        flexDirection: 'row',
        gap: 12,
        marginBottom: 16,
    },
    externosInputGroup: {
        flex: 1,
        marginBottom: 16,
    },
    externosInputLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#495057',
        marginBottom: 8,
        flexDirection: 'row',
        alignItems: 'center',
    },
    externosPickerWrapper: {
        backgroundColor: '#fff',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#dee2e6',
        elevation: 1,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    externosPicker: {
        height: 50,
        paddingHorizontal: 12,
    },
    externosTextInput: {
        backgroundColor: '#fff',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#dee2e6',
        paddingHorizontal: 15,
        paddingVertical: 12,
        fontSize: 16,
        elevation: 1,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    externosCategoryButtons: {
        flexDirection: 'row',
        gap: 10,
    },
    externosCategoryButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#1792FE',
        backgroundColor: '#fff',
        gap: 8,
    },
    externosCategoryButtonActive: {
        backgroundColor: '#1792FE',
        borderColor: '#1792FE',
    },
    externosCategoryButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#1792FE',
    },
    externosCategoryButtonTextActive: {
        color: '#fff',
    },
    externosCheckboxContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#1792FE',
        backgroundColor: '#fff',
        gap: 8,
    },
    externosCheckboxContainerActive: {
        backgroundColor: '#1792FE',
        borderColor: '#1792FE',
    },
    externosCheckboxText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#1792FE',
    },
    externosCheckboxTextActive: {
        color: '#fff',
    },
    externosAddButton: {
        borderRadius: 12,
        overflow: 'hidden',
        marginTop: 10,
        elevation: 3,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
    },
    externosAddButtonGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 14,
        paddingHorizontal: 20,
        gap: 8,
    },
    externosAddButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '700',
    },
    externosListCard: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 20,
        borderWidth: 1,
        borderColor: '#e9ecef',
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    externosListTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#333',
        marginBottom: 15,
        textAlign: 'center',
    },
    externosListItem: {
        flexDirection: 'row',
        backgroundColor: '#f8f9fa',
        borderRadius: 12,
        padding: 15,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#e9ecef',
        alignItems: 'center',
    },
    externosListItemContent: {
        flex: 1,
    },
    externosListItemHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 6,
    },
    externosListItemName: {
        fontSize: 16,
        fontWeight: '700',
        color: '#333',
        flex: 1,
    },
    externosListItemBadge: {
        backgroundColor: '#1792FE',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
    },
    externosListItemBadgeText: {
        color: '#fff',
        fontSize: 12,
        fontWeight: '700',
    },
    externosListItemDetails: {
        fontSize: 13,
        color: '#666',
        marginBottom: 4,
        lineHeight: 18,
    },
    externosListItemCategory: {
        fontSize: 12,
        color: '#495057',
        fontStyle: 'italic',
    },
    externosListItemObservations: {
        fontSize: 11,
        color: '#1792FE',
        marginTop: 4,
        fontStyle: 'italic',
    },
    externosListItemDelete: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: 10,
        elevation: 2,
        shadowColor: '#dc3545',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 2,
    },
    externosSubmitButton: {
        borderRadius: 12,
        overflow: 'hidden',
        marginTop: 15,
        elevation: 3,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
    },
    externosSubmitButtonDisabled: {
        elevation: 0,
        shadowOpacity: 0,
    },
    externosSubmitButtonGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 14,
        paddingHorizontal: 20,
        gap: 8,
    },
    externosSubmitButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '700',
    },

    // Modal de edição
    editModalContainer: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 10,
    },
    editModalContent: {
        backgroundColor: '#FFFFFF',
        width: '100%',
        maxWidth: 900,
        maxHeight: '90%',
        borderRadius: 20,
        elevation: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 5 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
        overflow: 'hidden',
    },
    editModalHeader: {
        paddingHorizontal: 20,
        paddingTop: 20,
        paddingBottom: 15,
    },
    editModalHeaderContent: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    editModalTitleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    editModalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#fff',
    },
    editModalSubtitle: {
        fontSize: 14,
        color: 'rgba(255,255,255,0.9)',
        marginTop: 5,
    },
    editCloseButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: 'rgba(255,255,255,0.2)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    editModalBody: {
        flex: 1,
        paddingHorizontal: 20,
        paddingTop: 15,
    },
    editInfoCard: {
        backgroundColor: '#f8f9fa',
        borderRadius: 16,
        padding: 20,
        marginBottom: 15,
        borderWidth: 1,
        borderColor: '#e9ecef',
    },
    editInfoTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#333',
        marginBottom: 15,
        textAlign: 'center',
    },
    editInfoGrid: {
        flexDirection: 'row',
        gap: 15,
        marginBottom: 12,
    },
    editInfoItem: {
        flex: 1,
    },
    editInfoLabel: {
        fontSize: 12,
        fontWeight: '600',
        color: '#666',
        marginBottom: 4,
    },
    editInfoValue: {
        fontSize: 14,
        fontWeight: '600',
        color: '#333',
    },
    editInfoFooter: {
        marginTop: 10,
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: '#e9ecef',
    },
    editInfoSubText: {
        fontSize: 12,
        color: '#666',
        textAlign: 'center',
        fontStyle: 'italic',
    },
    editNoteCard: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 14,
        marginBottom: 15,
        borderWidth: 1,
        borderColor: '#e9ecef',
    },
    editNoteLabel: {
        fontSize: 13,
        fontWeight: '600',
        color: '#495057',
        marginBottom: 8,
    },
    editNoteInput: {
        backgroundColor: '#f8f9fa',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#dee2e6',
        paddingHorizontal: 12,
        paddingVertical: 10,
        fontSize: 14,
        minHeight: 70,
    },
    tableHeader: {
        flexDirection: 'row',
        backgroundColor: '#1792FE',
        minHeight: 50,
    },
    fixedColumn: {
        backgroundColor: '#f5f5f5',
    },
    headerText: {
        fontSize: 12,
        fontWeight: 'bold',
        color: '#FFFFFF',
        textAlign: 'center',
    },
    variacaoText: {
        fontSize: 12,
        fontWeight: '600',
    },
    editingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#e3f2fd',
        borderRadius: 4,
        margin: 2,
    },
    horasInputInline: {
        width: 40,
        height: 30,
        borderWidth: 1,
        borderColor: '#1792FE',
        borderRadius: 4,
        padding: 2,
        fontSize: 12,
        textAlign: 'center',
        backgroundColor: '#fff',
    },
    confirmSubText: {
        fontSize: 14,
        color: '#666',
        textAlign: 'center',
        marginBottom: 20,
    },
    editInfo: {
        backgroundColor: '#f8f9fa',
        padding: 15,
        borderRadius: 8,
        marginBottom: 20,
    },
    editInfoText: {
        fontSize: 14,
        color: '#333',
        marginBottom: 5,
    },
    inputGroup: {
        marginBottom: 20,
    },
    inputLabel: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
        marginBottom: 10,
    },
    pickerContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    pickerOption: {
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 20,
        backgroundColor: '#f0f0f0',
        marginBottom: 8,
    },
    pickerOptionSelected: {
        backgroundColor: '#1792FE',
    },
    pickerOptionText: {
        fontSize: 14,
        color: '#666',
    },
    pickerOptionTextSelected: {
        color: '#FFFFFF',
        fontWeight: '600',
    },
    especialidadesContainer: {
        marginBottom: 20,
    },
    especialidadesHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 15,
    },
    addButton: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    addButtonText: {
        color: '#28a745',
        fontWeight: '600',
        marginLeft: 5,
    },
    especialidadeItem: {
        backgroundColor: '#f8f9fa',
        padding: 15,
        borderRadius: 8,
        marginBottom: 15,
        borderWidth: 1,
        borderColor: '#e0e0e0',
    },
    especialidadeHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 10,
    },
    especialidadeTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
    },
    removeButton: {
        padding: 5,
    },
    inputRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 10,
    },
    inputHalf: {
        flex: 0.48,
    },
    inputLabelSmall: {
        fontSize: 14,
        fontWeight: '600',
        color: '#333',
        marginBottom: 8,
    },
    horasInput: {
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 8,
        padding: 12,
        fontSize: 16,
        backgroundColor: '#fff',
    },
    pickerOptionSmall: {
        paddingVertical: 6,
        paddingHorizontal: 10,
        borderRadius: 15,
        backgroundColor: '#f0f0f0',
        marginBottom: 6,
        marginRight: 6,
    },
    pickerOptionTextSmall: {
        fontSize: 12,
        color: '#666',
    },
    totalHoras: {
        backgroundColor: '#e8f4f8',
        padding: 12,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#1792FE',
    },
    totalHorasText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#1792FE',
        textAlign: 'center',
    },
    editSpecialitiesCard: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 20,
        borderWidth: 1,
        borderColor: '#e9ecef',
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    editSpecialitiesHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    editSpecialitiesTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#333',
        flex: 1,
    },
    editAddButton: {
        borderRadius: 12,
        overflow: 'hidden',
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 2,
    },
    editAddButtonGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 10,
        paddingHorizontal: 16,
        gap: 6,
    },
    editAddButtonText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '700',
    },
    editSpecialityItem: {
        backgroundColor: '#f8f9fa',
        borderRadius: 12,
        padding: 16,
        marginBottom: 15,
        borderWidth: 1,
        borderColor: '#e9ecef',
    },
    editSpecialityHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 15,
    },
    editSpecialityNumber: {
        fontSize: 14,
        fontWeight: '700',
        color: '#333',
        flex: 1,
    },
    editSpecialityActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    editHoraExtraButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#1792FE',
        backgroundColor: '#fff',
        gap: 4,
    },
    editHoraExtraButtonActive: {
        backgroundColor: '#1792FE',
        borderColor: '#1792FE',
    },
    editHoraExtraText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#1792FE',
    },
    editHoraExtraTextActive: {
        color: '#fff',
    },
    editRemoveButton: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
        elevation: 1,
        shadowColor: '#dc3545',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 2,
        borderWidth: 1,
        borderColor: '#1792FE',
    },
    editSpecialityGrid: {
        flexDirection: 'row',
        gap: 12,
        marginBottom: 16,
    },
    editInputGroup: {
        flex: 1,
        marginBottom: 16,
    },
    editInputLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#495057',
        marginBottom: 8,
    },
    editPickerWrapper: {
        backgroundColor: '#fff',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#dee2e6',
        elevation: 1,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    editPicker: {
        height: 50,
        paddingHorizontal: 12,
    },
    editTextInput: {
        backgroundColor: '#fff',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#dee2e6',
        paddingHorizontal: 15,
        paddingVertical: 12,
        fontSize: 16,
        elevation: 1,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    editCategoryButtons: {
        flexDirection: 'row',
        gap: 10,
    },
    editCategoryButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#1792FE',
        backgroundColor: '#fff',
        gap: 8,
    },
    editCategoryButtonActive: {
        backgroundColor: '#1792FE',
        borderColor: '#1792FE',
    },
    editCategoryButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#1792FE',
    },
    editCategoryButtonTextActive: {
        color: '#fff',
    },
    editHoursSummary: {
        backgroundColor: '#e3f2fd',
        borderRadius: 12,
        padding: 16,
        marginTop: 10,
        borderWidth: 1,
        borderColor: '#1792FE',
    },
    editHoursSummaryContent: {
        alignItems: 'center',
    },
    editHoursSummaryLabel: {
        fontSize: 14,
        fontWeight: '700',
        color: '#1792FE',
        marginBottom: 10,
    },
    editHoursSummaryValues: {
        alignItems: 'center',
        gap: 6,
    },
    editHoursSummaryText: {
        fontSize: 13,
        color: '#666',
        textAlign: 'center',
    },
    editSubmitButton: {
        borderRadius: 12,
        overflow: 'hidden',
        marginTop: 20,
        elevation: 3,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
    },
    editSubmitButtonGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 16,
        paddingHorizontal: 20,
        gap: 10,
    },
    editSubmitButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '700',
    },

    // Estilos principais
    header: {
        paddingTop: 50,
        paddingBottom: 20,
        paddingHorizontal: 20,
        alignItems: 'center',
    },
    headerTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#FFFFFF',
        marginBottom: 5,
    },
    headerSubtitle: {
        fontSize: 16,
        color: 'rgba(255,255,255,0.9)',
    },
    controlsContainer: {
        backgroundColor: '#FFFFFF',
        padding: 15,
        marginHorizontal: 10,
        marginVertical: 10,
        borderRadius: 10,
        elevation: 2,
    },
    monthSelector: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 15,
    },
    monthButton: {
        padding: 10,
        borderRadius: 20,
        backgroundColor: '#f0f0f0',
    },
    monthText: {
        fontSize: 18,
        fontWeight: '600',
        color: '#333',
        marginHorizontal: 20,
        textTransform: 'capitalize',
    },
    actionButtons: {
        flexDirection: 'row',
        justifyContent: 'flex-start',
        flexWrap: 'wrap',
        gap: 8,
        paddingHorizontal: 5,
    },
    actionButton: {
        borderRadius: 8,
        overflow: 'hidden',
        minWidth: '48%',
        maxWidth: '48%',
        marginBottom: 8,
    },
    buttonGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
        paddingHorizontal: 8,
        gap: 6,
    },
    buttonText: {
        color: '#FFFFFF',
        fontSize: 12,
        fontWeight: '600',
        textAlign: 'center',
        flexShrink: 1,
        numberOfLines: 1,
    },
    tableContainer: {
        flex: 1,
        margin: 10,
        borderRadius: 10,
        elevation: 2,
    },
    tableRow: {
        flexDirection: 'row',
        height: 50,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
    },
    evenRow: {
        backgroundColor: '#FFFFFF',
    },
    oddRow: {
        backgroundColor: '#f9f9f9',
    },
    tableCell: {
        padding: 10,
        justifyContent: 'center',
        borderRightWidth: 1,
        borderRightColor: '#e0e0e0',
        alignSelf: 'stretch',
        overflow: 'hidden',
    },
    cellText: {
        fontSize: 12,
        color: '#333',
    },
    cellSubText: {
        fontSize: 10,
        color: '#666',
        marginTop: 2,
    },
    hoursText: {
        fontWeight: '600',
        color: '#1792FE',
    },
    clickableHours: {
        textDecorationLine: 'underline',
    },
    totalText: {
        fontWeight: 'bold',
        color: '#333',
        fontSize: 13,
    },
    tableWrapper: {
        flex: 1,
        margin: 10,
        borderRadius: 10,
        elevation: 2,
    },
    tableInstructions: {
        fontSize: 12,
        color: '#666',
        padding: 10,
        backgroundColor: '#f8f9fa',
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        textAlign: 'center',
        borderBottomWidth: 1,
        borderBottomColor: '#e0e0e0',
    },
    horizontalScroll: {
        flex: 1,
    },
    tableContent: {
        minWidth: '100%',
    },
    cellTouchable: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        minHeight: 40,
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 40,
    },
    emptyText: {
        fontSize: 16,
        color: '#666',
        textAlign: 'center',
        marginTop: 20,
    },
    emptySubText: {
        fontSize: 14,
        color: '#999',
        textAlign: 'center',
        marginTop: 10,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
        backgroundColor: '#d4e4ff',
    },
    loadingText: {
        fontSize: 16,
        color: '#1792FE',
        marginTop: 10,
        marginBottom: 20,
    },
    progressContainer: {
        width: '80%',
        alignItems: 'center',
    },
    progressBar: {
        width: '100%',
        height: 8,
        backgroundColor: '#e0e0e0',
        borderRadius: 4,
        overflow: 'hidden',
    },
    progressFill: {
        height: '100%',
        backgroundColor: '#1792FE',
        borderRadius: 4,
    },
    progressText: {
        fontSize: 14,
        color: '#666',
        marginTop: 8,
    },
    modalContainer: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        backgroundColor: '#FFFFFF',
        width: '90%',
        maxHeight: '80%',
        borderRadius: 15,
        elevation: 5,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#333',
    },
    closeButton: {
        padding: 5,
    },
    modalBody: {
        padding: 20,
    },
    confirmText: {
        fontSize: 16,
        color: '#333',
        textAlign: 'center',
        marginBottom: 15,
    },
    confirmButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    confirmButton: {
        flex: 1,
        marginHorizontal: 5,
        borderRadius: 8,
        overflow: 'hidden',
    },
    cancelButton: {
        backgroundColor: '#f8f9fa',
        paddingVertical: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    cancelButtonText: {
        color: '#666',
        fontSize: 14,
        fontWeight: '600',
    },
    submitButton: {
        marginTop: 20,
        borderRadius: 8,
        overflow: 'hidden',
    },
    obraHeader: {
        backgroundColor: '#f0f8ff',
        borderBottomWidth: 2,
        borderBottomColor: '#1792FE',
        borderTopWidth: 2,
        borderTopColor: '#1792FE',
        paddingVertical: 12,
        paddingHorizontal: 15,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 10,
    },
    obraHeaderContent: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    obraHeaderText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#1792FE',
        marginRight: 8,
    },
    obraHeaderCode: {
        fontSize: 14,
        color: '#666',
        fontWeight: '500',
    },
    obraStats: {
        alignItems: 'flex-end',
    },
    obraStatsText: {
        fontSize: 12,
        color: '#1792FE',
        fontWeight: '600',
        marginBottom: 2,
    },
    trabalhadoresRow: {
        marginLeft: 0,
        borderLeftWidth: 0,
        borderLeftColor: '#e3f2fd',
    },
    obraSeparator: {
        height: 15,
        backgroundColor: '#f5f5f5',
        borderTopWidth: 1,
        borderTopColor: '#e0e0e0',
        marginVertical: 5,
    },
    cellSubmetido: {
        backgroundColor: '#e6f9e6',
    },
    iconSubmetido: {
        position: 'absolute',
        top: 2,
        right: 2,
    },
    obraDaysHeader: {
        flexDirection: 'row',
        backgroundColor: '#e3f2fd',
        height: 50,
        borderBottomWidth: 1,
        borderBottomColor: '#1792FE',
    },
    obraDaysHeaderText: {
        fontSize: 11,
        fontWeight: 'bold',
        color: '#1792FE',
        textAlign: 'center',
    },

    // Resumo Modal styles
    resumoModalContainer: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 10,
    },
    resumoModalContent: {
        width: '100%',
        maxWidth: 900,
        maxHeight: '90%',
        backgroundColor: '#fff',
        borderRadius: 15,
        overflow: 'hidden',
        elevation: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 5 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
    },
    resumoModalHeader: {
        padding: 20,
        paddingBottom: 15,
    },
    resumoModalHeaderContent: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 10,
    },
    resumoModalTitleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    resumoModalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#fff',
        marginLeft: 10,
    },
    resumoModalSubtitle: {
        fontSize: 14,
        color: 'rgba(255, 255, 255, 0.9)',
        marginTop: 5,
    },
    resumoCloseButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    resumoModalBody: {
        flex: 1,
        padding: 15,
        backgroundColor: '#fff',
    },
    resumoStatsCard: {
        backgroundColor: '#f8f9fa',
        borderRadius: 12,
        padding: 18,
        marginBottom: 15,
        borderWidth: 1,
        borderColor: '#e9ecef',
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    resumoStatsTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#333',
        marginBottom: 15,
        textAlign: 'center',
    },
    resumoStatsGrid: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        flexWrap: 'wrap',
        gap: 10,
    },
    resumoStatItem: {
        alignItems: 'center',
        minWidth: 80,
        paddingVertical: 8,
    },
    resumoStatNumber: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#1792FE',
    },
    resumoStatLabel: {
        fontSize: 11,
        color: '#666',
        marginTop: 5,
        textAlign: 'center',
    },
    resumoSectionCard: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 16,
        marginBottom: 15,
        borderWidth: 1,
        borderColor: '#e9ecef',
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    resumoSectionTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#333',
        marginBottom: 15,
        flexDirection: 'row',
        alignItems: 'center',
    },
    resumoTrabalhadorItem: {
        backgroundColor: '#f8f9fa',
        borderRadius: 8,
        padding: 12,
        marginBottom: 10,
    },
    resumoTrabalhadorHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    resumoTrabalhadorNome: {
        fontSize: 14,
        fontWeight: '600',
        color: '#333',
        flex: 1,
    },
    resumoTrabalhadorBadges: {
        flexDirection: 'row',
    },
    resumoTrabalhadorBadge: {
        backgroundColor: '#1792FE',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
        marginLeft: 5,
        flexDirection: 'row',
        alignItems: 'center',
    },
    resumoTrabalhadorBadgeExtra: {
        backgroundColor: '#ff6b35',
    },
    resumoTrabalhadorBadgeText: {
        fontSize: 11,
        color: '#fff',
        fontWeight: '600',
        marginLeft: 2,
    },
    resumoDiaItem: {
        backgroundColor: '#fff',
        borderRadius: 6,
        padding: 8,
        marginBottom: 5,
    },
    resumoDiaInfo: {
        fontSize: 12,
        color: '#666',
        marginBottom: 3,
    },
    resumoDiaDetalhes: {
        fontSize: 11,
        color: '#999',
    },
    resumoObraExternos: {
        marginBottom: 15,
    },
    resumoObraExternosTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: '#1792FE',
        marginBottom: 8,
    },
    resumoExternoItem: {
        backgroundColor: '#f8f9fa',
        borderRadius: 6,
        padding: 10,
        marginBottom: 8,
    },
    resumoExternoHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 5,
    },
    resumoExternoNome: {
        fontSize: 13,
        fontWeight: '600',
        color: '#333',
        flex: 1,
    },
    resumoExternoBadges: {
        flexDirection: 'row',
    },
    resumoExternoBadge: {
        backgroundColor: '#6c757d',
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 8,
        marginLeft: 4,
        flexDirection: 'row',
        alignItems: 'center',
    },
    resumoExternoBadgeExtra: {
        backgroundColor: '#ff6b35',
    },
    resumoExternoBadgeText: {
        fontSize: 10,
        color: '#fff',
        fontWeight: '500',
    },
    resumoExternoDetalhes: {
        fontSize: 11,
        color: '#666',
        lineHeight: 16,
    },
    resumoExternoObservations: {
        fontSize: 11,
        color: '#1792FE',
        marginTop: 4,
        fontStyle: 'italic',
    },
    resumoListItemObservations: {
        fontSize: 11,
        color: '#1792FE',
        marginTop: 4,
        fontStyle: 'italic',
    },
    resumoEmptyCard: {
        alignItems: 'center',
        padding: 40,
    },
    resumoEmptyText: {
        fontSize: 16,
        color: '#666',
        marginTop: 15,
        fontWeight: '600',
    },
    resumoEmptySubText: {
        fontSize: 14,
        color: '#999',
        marginTop: 5,
        textAlign: 'center',
    },
    resumoModalFooter: {
        flexDirection: 'row',
        padding: 15,
        backgroundColor: '#f8f9fa',
        borderTopWidth: 1,
        borderTopColor: '#e9ecef',
        gap: 10,
    },
    resumoCancelButton: {
        flex: 1,
        padding: 15,
        borderRadius: 10,
        backgroundColor: '#6c757d',
        alignItems: 'center',
        justifyContent: 'center',
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
    },
    resumoCancelButtonText: {
        color: '#fff',
        fontSize: 15,
        fontWeight: '600',
    },
    resumoConfirmButton: {
        flex: 2,
        borderRadius: 10,
        overflow: 'hidden',
        elevation: 3,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
    },
    resumoConfirmButtonDisabled: {
        opacity: 0.5,
        elevation: 0,
        shadowOpacity: 0,
    },
    resumoConfirmButtonGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        paddingHorizontal: 20,
        gap: 8,
    },
    resumoConfirmButtonText: {
        color: '#fff',
        fontSize: 15,
        fontWeight: '700',
    },
});